@startuml

class 问题生成模块 {
}
class 答案处理模块 {
}
class 统计模块 {
}
class 计时模块 {
}
class 反馈模块 {
}
class 界面模块 {
}

问题生成模块--|>界面模块
答案处理模块--|>界面模块
统计模块--|>界面模块
计时模块--|>界面模块
反馈模块--|>界面模块
答案处理模块--|>反馈模块
答案处理模块--|>统计模块
问题生成模块--|>答案处理模块
@enduml
